-- Silver: cleaned and enriched vacancy_snapshot from bronze
-- Auto-generated by `platform add-entity`. Add joins and business logic.

with bronze as (

    select * from {{ ref('brz_job_market_nl__it_market_snapshot') }}

),

enriched as (

    select
        *
    from bronze

)

select * from enriched
