-- Silver: cleaned and enriched job_posting from bronze
-- Auto-generated by `platform add-entity`. Add joins and business logic.

with bronze as (

    select * from {{ ref('brz_odp_staffing_demand__harvey_nash_vacatures') }}

),

enriched as (

    select
        *
    from bronze

)

select * from enriched
