#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

COMPOSE_FILE="${COMPOSE_MINIMAL_FILE:-docker-compose.minimal.yml}"
WAIT_TIMEOUT_SECONDS="${COMPOSE_MINIMAL_WAIT_TIMEOUT_SECONDS:-120}"
RETRY_INTERVAL_SECONDS="${COMPOSE_MINIMAL_RETRY_INTERVAL_SECONDS:-2}"
DASHBOARD_WAIT_TIMEOUT_SECONDS="${COMPOSE_MINIMAL_DASHBOARD_WAIT_TIMEOUT_SECONDS:-45}"

PASS_COUNT=0
FAIL_COUNT=0

log() {
  echo "[verify-compose-minimal] $*"
}

record_result() {
  local status="$1"
  local check_name="$2"
  local detail="$3"

  case "$status" in
    GREEN) PASS_COUNT=$((PASS_COUNT + 1)) ;;
    RED) FAIL_COUNT=$((FAIL_COUNT + 1)) ;;
  esac

  printf '%-5s | %-30s | %s\n' "$status" "$check_name" "$detail"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

container_state() {
  local container="$1"
  local resolved
  resolved="$(resolve_container_ref "$container")"
  if [[ -z "$resolved" ]]; then
    return 0
  fi
  docker inspect -f '{{.State.Status}}' "$resolved" 2>/dev/null || true
}

container_exit_code() {
  local container="$1"
  local resolved
  resolved="$(resolve_container_ref "$container")"
  if [[ -z "$resolved" ]]; then
    return 0
  fi
  docker inspect -f '{{.State.ExitCode}}' "$resolved" 2>/dev/null || true
}

resolve_container_ref() {
  local ref="$1"

  # First try direct container lookup for services with explicit container_name.
  if docker inspect "$ref" >/dev/null 2>&1; then
    echo "$ref"
    return 0
  fi

  # Fall back to compose service lookup for autogenerated names like
  # <project>-create-buckets-1.
  local cid
  cid="$(docker compose -f "$COMPOSE_FILE" ps -aq "$ref" 2>/dev/null | head -n 1)"
  if [[ -n "$cid" ]]; then
    echo "$cid"
  fi
}

wait_for_container_state() {
  local check_name="$1"
  local container="$2"
  local expected_state="$3"
  local deadline=$(( $(date +%s) + WAIT_TIMEOUT_SECONDS ))

  while (( $(date +%s) <= deadline )); do
    local state
    state="$(container_state "$container")"
    if [[ "$state" == "$expected_state" ]]; then
      record_result "GREEN" "$check_name" "container=$container state=$state"
      return 0
    fi
    sleep "$RETRY_INTERVAL_SECONDS"
  done

  local final_state
  final_state="$(container_state "$container")"
  record_result "RED" "$check_name" "container=$container expected=$expected_state got=${final_state:-missing}"
}

wait_for_container_exit_zero() {
  local check_name="$1"
  local container="$2"
  local deadline=$(( $(date +%s) + WAIT_TIMEOUT_SECONDS ))

  while (( $(date +%s) <= deadline )); do
    local state exit_code
    state="$(container_state "$container")"
    exit_code="$(container_exit_code "$container")"
    if [[ "$state" == "exited" && "$exit_code" == "0" ]]; then
      record_result "GREEN" "$check_name" "container=$container exited=0"
      return 0
    fi
    sleep "$RETRY_INTERVAL_SECONDS"
  done

  local final_state final_code
  final_state="$(container_state "$container")"
  final_code="$(container_exit_code "$container")"
  record_result "RED" "$check_name" "container=$container expected=exited(0) got=${final_state:-missing}(${final_code:-n/a})"
}

wait_for_http() {
  local check_name="$1"
  local url="$2"
  local expected_codes="$3"
  local deadline=$(( $(date +%s) + WAIT_TIMEOUT_SECONDS ))

  while (( $(date +%s) <= deadline )); do
    local code
    code="$(curl -sS -o /dev/null -w '%{http_code}' "$url" || true)"
    if [[ ",$expected_codes," == *",$code,"* ]]; then
      record_result "GREEN" "$check_name" "code=$code url=$url"
      return 0
    fi
    sleep "$RETRY_INTERVAL_SECONDS"
  done

  local final_code
  final_code="$(curl -sS -o /dev/null -w '%{http_code}' "$url" || true)"
  record_result "RED" "$check_name" "code=$final_code expected=$expected_codes url=$url"
}

wait_for_superset_dashboards() {
  local check_name="$1"
  local deadline=$(( $(date +%s) + DASHBOARD_WAIT_TIMEOUT_SECONDS ))
  local titles

  while (( $(date +%s) <= deadline )); do
    titles="$(docker exec open-data-platform-superset sh -lc 'python - <<"PY"
import sqlite3
conn = sqlite3.connect("/app/superset_home/superset.db")
cur = conn.cursor()
cur.execute("select dashboard_title from dashboards")
print("\\n".join(sorted([row[0] for row in cur.fetchall()])))
PY' 2>/dev/null || true)"

    if echo "$titles" | grep -q "NL IT Job Market" \
      && echo "$titles" | grep -q "ODP Staffing Demand" \
      && echo "$titles" | grep -q "Platform Metadata Operations"; then
      record_result "GREEN" "$check_name" "seeded dashboards present"
      return 0
    fi
    sleep "$RETRY_INTERVAL_SECONDS"
  done

  record_result "RED" "$check_name" "missing expected dashboards (found: ${titles:-none})"
}

main() {
  require_cmd docker
  require_cmd curl

  if ! docker compose -f "$COMPOSE_FILE" config >/dev/null 2>&1; then
    echo "Compose file is invalid or missing: $COMPOSE_FILE" >&2
    exit 1
  fi

  echo "STATUS | CHECK                          | DETAIL"
  echo "-------+--------------------------------+-----------------------------------------------"

  # Long-running services
  wait_for_container_state "Airflow webserver container" "airflow-webserver" "running"
  wait_for_container_state "Airflow scheduler container" "airflow-scheduler" "running"
  wait_for_container_state "Airflow Postgres container" "airflow-postgres" "running"
  wait_for_container_state "Keycloak container" "open-data-platform-keycloak" "running"
  wait_for_container_state "MinIO container" "open-data-platform-minio" "running"
  wait_for_container_state "MinIO SSO bridge container" "open-data-platform-minio-sso-bridge" "running"
  wait_for_container_state "Warehouse container" "open-data-platform-warehouse" "running"
  wait_for_container_state "Superset container" "open-data-platform-superset" "running"
  wait_for_container_state "Superset DB container" "superset-postgres" "running"
  wait_for_container_state "Portal container" "open-data-platform-portal" "running"
  wait_for_container_state "dbt docs container" "open-data-platform-dbt-docs" "running"
  wait_for_container_state "Portal API container" "open-data-platform-portal-api" "running"

  # One-shot setup services
  wait_for_container_exit_zero "Airflow init completed" "airflow-init"
  wait_for_container_exit_zero "MinIO buckets created" "create-buckets"

  # HTTP smoke checks
  wait_for_http "Airflow health" "http://localhost:8080/health" "200"
  wait_for_http "Keycloak OIDC discovery" "http://localhost:8090/realms/odp/.well-known/openid-configuration" "200"
  wait_for_http "MinIO live health" "http://localhost:9000/minio/health/live" "200"
  wait_for_http "MinIO console" "http://localhost:9001/" "200,302,307"
  wait_for_http "MinIO SSO bridge" "http://localhost:9011/start" "200,302,303"
  wait_for_http "Superset health" "http://localhost:8088/health" "200"
  wait_for_superset_dashboards "Superset seeded dashboards"
  wait_for_http "Portal root" "http://localhost:3000/" "200"
  wait_for_http "dbt docs root" "http://localhost:8089/" "200"
  wait_for_http "Portal API health" "http://localhost:8070/healthz" "200"

  echo
  echo "Summary: GREEN=$PASS_COUNT RED=$FAIL_COUNT"

  if (( FAIL_COUNT > 0 )); then
    log "Minimal compose smoke checks failed."
    exit 1
  fi

  log "All minimal compose smoke checks passed."
}

main "$@"
